- hosts:
    - rpis
  tags:
    - ngrok
  sudo: yes
    
  tasks:
    - name: Make sure unzip is installed
      apt: name=unzip state=latest

    - name: Make sure wget is installed
      apt: name=wget state=latest

    - name: Download ngrok
      command: wget https://dl.ngrok.com/ngrok_2.0.17_linux_arm.zip
    
    - name: Unzip ngrok
      command: unzip ngrok_2.0.17_linux_arm.zip

